/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComprehensionQuestion.java
 *
 * Created on Nov 23, 2012, 10:04:55 PM
 */

package utme;

import java.awt.Color;
import java.awt.GridLayout;
import java.io.IOException;
import java.net.URL;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;

/**
 *
 * @author ADmin
 */
public class ComprehensionQuestion extends QuestionPanel {

    /** Creates new form ComprehensionQuestion */
    private Comprehension comprehension;
    private int noOfOptions;
    private JRadioButton [] options;
    private ButtonGroup buttonGroup;
    private URL helpURl;
    public ComprehensionQuestion(Comprehension comprehension, int questionNumber) {
        super();
        initComponents();
        //tabMe.setSelectedIndex(0);
        this.comprehension = comprehension;
        setQuestionNumberLabel(questionNumber);
        setQuestion();
        setOptionPanel();
        setpassage();
        setInstruction();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        instructionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        passageText = new javax.swing.JEditorPane();
        jSeparator1 = new javax.swing.JSeparator();
        tabMe = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        questionArea = new javax.swing.JEditorPane();
        questionNumberLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        optionPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 0));
        setPreferredSize(new java.awt.Dimension(438, 385));

        instructionLabel.setForeground(new java.awt.Color(51, 0, 0));
        instructionLabel.setText("Use the information in the  passage to answer questions");

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 0));
        jScrollPane1.setForeground(new java.awt.Color(204, 153, 0));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(108, 25));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(108, 232));

        passageText.setEditable(false);
        passageText.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        passageText.setForeground(new java.awt.Color(51, 0, 255));
        passageText.setPreferredSize(new java.awt.Dimension(106, 180));
        jScrollPane1.setViewportView(passageText);

        jSeparator1.setBackground(new java.awt.Color(255, 204, 0));

        tabMe.setBackground(new java.awt.Color(255, 204, 0));
        tabMe.setFont(new java.awt.Font("Tahoma", 1, 12));

        jScrollPane3.setBackground(new java.awt.Color(255, 204, 0));

        questionArea.setEditable(false);
        questionArea.setMinimumSize(new java.awt.Dimension(86, 20));
        questionArea.setPreferredSize(new java.awt.Dimension(86, 20));
        jScrollPane3.setViewportView(questionArea);

        tabMe.addTab("Question", jScrollPane3);

        questionNumberLabel.setForeground(new java.awt.Color(51, 0, 0));
        questionNumberLabel.setText("1");

        optionPanel.setPreferredSize(new java.awt.Dimension(138, 180));

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(optionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabMe, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(instructionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(questionNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructionLabel)
                    .addComponent(questionNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tabMe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

/*public static void main(String [] args)
{
    JFrame frame = new JFrame();
    Comprehension ques = new Comprehension(2, 1, 1);
    ComprehensionQuestion q = new ComprehensionQuestion(ques, 1);
    frame.setSize(600,500);
    frame.add(new JScrollPane(q));
    frame.setVisible(true);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
}*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JEditorPane passageText;
    private javax.swing.JEditorPane questionArea;
    private javax.swing.JLabel questionNumberLabel;
    private javax.swing.JTabbedPane tabMe;
    // End of variables declaration//GEN-END:variables

    private void setQuestion()
    {
        questionArea.setText(comprehension.getQuestion());
    }

    private void setOptionPanel()
    {
      noOfOptions = comprehension.getNoOfOptions();
      optionPanel.setLayout(new GridLayout(noOfOptions, 1));
      options = new JRadioButton[noOfOptions];
      String optionStrings[] = comprehension.getOptions();
      buttonGroup = new ButtonGroup();
      for(int i = 0; i < options.length; i++)
      {
          options[i] = new JRadioButton(optionStrings[i]);
          options[i].setBackground(Color.white);
          optionPanel.add(options[i]);
          buttonGroup.add(options[i]);
      }
    }

    private void setpassage()
    {
        helpURl = comprehension.getURL();
        if (helpURl != null) {
    try {
        passageText.setPage(helpURl);
    } catch (IOException e) {
        System.err.println("Attempted to read a bad URL: " + helpURl);
    }
} else {
    System.err.println("Couldn't find file: ");
}

    }

    private void setInstruction() {
        instructionLabel.setText(comprehension.getInstruction());
    }
    @Override
    public int getSelectedIndex()
    {
       int selected = -1;
       for(int i=0; i< options.length; i++)
       {
           if(options[i].isSelected())
           {
               selected = i + 1;
           }
       }
       return selected;
    }
    @Override
    public int getAnswer()
    {
        int s = comprehension.getAnswer();
        return s;
    }
    @Override
    public void clear()
    {
        buttonGroup.clearSelection();
        for(JRadioButton but:options)
        {
            but.setEnabled(false);
        }
    }
    @Override
    public void clearSelection()
    {
        buttonGroup.clearSelection();
    }
    @Override
    public void selectSpecific(int index)
    {
        options[index -1].setSelected(true);
        options[index -1].setEnabled(true);
        //String text = options[index - 1].getText();
        options[index -1].setForeground(Color.GREEN);
        //options[index - 1].setText(text);
        options[index -1].setToolTipText("Correct answer");
    }

    private void setQuestionNumberLabel(int questionNumber) {
        questionNumberLabel.setText("QUESTION: " + questionNumber);
    }
    @Override
    public void enableAll()
    {
        //optionGroup.clearSelection();
        for(JRadioButton but:options)
        {
            but.setEnabled(true);
            but.setForeground(Color.black);
            but.setToolTipText("");
        }
    }

}
