/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultDialog.java
 *
 * Created on Nov 23, 2012, 12:24:07 AM
 */

package utme;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author ADmin
 */
public class ResultDialog extends javax.swing.JDialog {

    /** Creates new form ResultDialog */
    private ResultInfo rinfo;
    private boolean condition = false;
    private QuestionPanel questions[];
    private QuestionInfo info;
    private Question[] questionArray;
    public ResultDialog(java.awt.Frame parent, boolean modal, ResultInfo rinfo, QuestionPanel[] questions, Question[] questionArray) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.rinfo = rinfo;
        this.questionArray = questionArray;
        setTitle("NAME: " + rinfo.getName());
        info = rinfo.getQuestionInfo();
        this.questions = questions;
        setScorePanel();
        getContentPane().setBackground(new Color(105, 243, 0));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scorePanel = new javax.swing.JPanel();
        review = new javax.swing.JButton();
        takeAnother = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        takeSameExam = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        takeSame = new javax.swing.JMenuItem();
        takeAnoth = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        scorePanel.setBackground(new java.awt.Color(102, 204, 0));
        scorePanel.setOpaque(false);

        javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );

        review.setBackground(new java.awt.Color(255, 0, 51));
        review.setFont(new java.awt.Font("Oregon LDO Medium Sinistral", 1, 12)); // NOI18N
        review.setText("REVIEW");
        review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewActionPerformed(evt);
            }
        });

        takeAnother.setBackground(new java.awt.Color(255, 0, 51));
        takeAnother.setFont(new java.awt.Font("Oregon LDO Medium Sinistral", 1, 12)); // NOI18N
        takeAnother.setText("take Another Exam");
        takeAnother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeAnotherActionPerformed(evt);
            }
        });

        takeSameExam.setBackground(new java.awt.Color(255, 0, 51));
        takeSameExam.setFont(new java.awt.Font("Oregon LDO Medium Sinistral", 1, 12)); // NOI18N
        takeSameExam.setText("take Same Exam");
        takeSameExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeSameExamActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Review");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        takeSame.setText("Take Same Exam");
        takeSame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeSameActionPerformed(evt);
            }
        });
        jMenu1.add(takeSame);

        takeAnoth.setText("Take Another Exam");
        takeAnoth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeAnothActionPerformed(evt);
            }
        });
        jMenu1.add(takeAnoth);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem5.setText("Review");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator3);

        jMenuItem7.setText("Take Same Exam");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Take Another Exam");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(review)
                        .addGap(2, 2, 2)
                        .addComponent(takeSameExam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(takeAnother))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(scorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(takeAnother)
                    .addComponent(review)
                    .addComponent(takeSameExam))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewActionPerformed
        // TODO add your handling code here:
        Review dialog = new Review(new javax.swing.JFrame(), true, rinfo, questions, questionArray);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                ResultDialog.this.dispose();
                dialog.setVisible(true);
    }//GEN-LAST:event_reviewActionPerformed

    private void takeAnotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeAnotherActionPerformed
        // TODO add your handling code here:
        QuestionsDialog dialog = new  QuestionsDialog(new javax.swing.JFrame(), true, info);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                       // System.exit(0);
                    }
                });
                ResultDialog.this.dispose();
                dialog.setVisible(true);
    }//GEN-LAST:event_takeAnotherActionPerformed

    private void takeSameExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeSameExamActionPerformed
        // TODO add your handling code here:
        QuestionsDialog dialog = new QuestionsDialog(new javax.swing.JFrame(), true,questionArray, rinfo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                ResultDialog.this.dispose();
                dialog.setVisible(true);
    }//GEN-LAST:event_takeSameExamActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Utility.paintAboutPage(AboutPages.Review, new JFrame(), true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Utility.paintAboutPage(AboutPages.Exit, new JFrame(), true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Utility.paintAboutPage(AboutPages.TakeSameExam, new JFrame(), true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Utility.paintAboutPage(AboutPages.TakeAnotherExam, new JFrame(), true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
                Review dialog = new Review(new javax.swing.JFrame(), true, rinfo, questions, questionArray);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                ResultDialog.this.dispose();
                dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ResultDialog.this.dispose();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void takeSameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeSameActionPerformed
        // TODO add your handling code here:
        
                QuestionsDialog dialog = new QuestionsDialog(new javax.swing.JFrame(), true,questionArray, rinfo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                ResultDialog.this.dispose();
                dialog.setVisible(true);
    }//GEN-LAST:event_takeSameActionPerformed

    private void takeAnothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeAnothActionPerformed
        // TODO add your handling code here:
        QuestionsDialog dialog = new  QuestionsDialog(new javax.swing.JFrame(), true, info);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                       // System.exit(0);
                    }
                });
                ResultDialog.this.dispose();
                dialog.setVisible(true);

    }//GEN-LAST:event_takeAnothActionPerformed

    /**
    * @param args the command line arguments
    */
  /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int s[] = {4, 6 ,7};
                String n[] = { "Physics", "cdf","dfewrf"};
                QuestionInfo p = null;
                ResultInfo info = new ResultInfo(2,3,10, s, "tunde",n , p);
                ResultDialog dialog = new ResultDialog(new javax.swing.JFrame(), true, info, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JButton review;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JMenuItem takeAnoth;
    private javax.swing.JButton takeAnother;
    private javax.swing.JMenuItem takeSame;
    private javax.swing.JButton takeSameExam;
    // End of variables declaration//GEN-END:variables

    private void setScorePanel() {
        //nameLabel.setText(rinfo.getName());
        String nameOfSubjects[] = rinfo.getNameOfSubjects();
        int number = nameOfSubjects.length;
        int [] scoresPS = rinfo.getScoresPerSubject();
        int score = rinfo.getScore();
        int pscore = rinfo.getPscore();
        if(pscore > 50)
        {
            condition = true;
        }
        int total = rinfo.getTotal();
        int numberOfQ = total/number;
        GridLayout grid = new GridLayout(number + 3, 2);
        scorePanel.setLayout(grid);
        //scorePanel.setBackground(Color.WHITE);
        scorePanel.setOpaque(false);
        grid.setVgap(25);
        JLabel labels[] = new JLabel[number + 3];
        JLabel labelsMark[] = new JLabel[number + 3];
        labels[0] = new JLabel("SUBJECT");
        labels[0].setForeground(new Color(102,51,0));
        labelsMark[0] = new JLabel("                     SCORE");
        labelsMark[0].setForeground(new Color(102,51,0));
       for(int i = 1; i < labels.length - 2; i++)
       {
           labels[i] = new JLabel(nameOfSubjects[i -1]);
           labels[i].setForeground(new Color(102,51,0));
           labelsMark[i] = new JLabel("                      " + scoresPS[i -1]+ " / " + numberOfQ);
       }
        labels[number + 1] = new JLabel("TOTAL:");
        labels[number + 1].setForeground(new Color(102,51,0));
        labelsMark[number + 1] = new JLabel("                    "+ score+ " / "+ total);
        labels[number + 2] = new JLabel("PERCENTAGE:");
        labels[number + 2].setForeground(new Color(102,51,0));
        labelsMark[number + 2] = new JLabel("                       " + pscore + " %");
        if(!condition)
        {
            labelsMark[number + 1].setForeground(Color.red);
            labelsMark[number + 2].setForeground(Color.red);
        }
 else
        {
            labelsMark[number + 1].setForeground(Color.BLUE);
            labelsMark[number + 2].setForeground(Color.BLUE);
 }
        for(int i = 0; i < labels.length; i++)
        {
            scorePanel.add(labels[i]);
            scorePanel.add(labelsMark[i]);
        }
    }

}
