/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * standardized.java
 *
 * Created on Nov 25, 2012, 1:23:03 PM
 */

package utme;

import java.awt.Color;
import java.awt.GridLayout;
//import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADmin
 */
public class standardized extends javax.swing.JPanel {
    private JCheckBox[] subjectBox;
    private int numberOfSubjects;
    private String nameOfStudent;
    private boolean isNameValid;

    /** Creates new form standardized */
    public standardized() {
        initComponents();
        setSubjectPanel();
    }
    private void setSubjectPanel()
    {
        String subjects [] = Utility.getSubjectTypes();
        int len = subjects.length;
        subjectPanel.setLayout(new GridLayout(len, 1));
        subjectBox  = new JCheckBox[len];
        for(int i = 0; i < len; i++)
        {
            subjectBox[i] = new JCheckBox(subjects[i]);
            subjectBox[i].setOpaque(false);
            subjectBox[i].setForeground(Color.BLUE);
            subjectPanel.add(subjectBox[i]);

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        start = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        cancelSelection = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 0));
        setPreferredSize(new java.awt.Dimension(228, 463));

        subjectPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 0, 20));
        subjectPanel.setOpaque(false);
        subjectPanel.setPreferredSize(new java.awt.Dimension(226, 309));

        javax.swing.GroupLayout subjectPanelLayout = new javax.swing.GroupLayout(subjectPanel);
        subjectPanel.setLayout(subjectPanelLayout);
        subjectPanelLayout.setHorizontalGroup(
            subjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        subjectPanelLayout.setVerticalGroup(
            subjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        start.setForeground(new java.awt.Color(0, 0, 204));
        start.setText("START");
        start.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        exit.setForeground(new java.awt.Color(0, 0, 204));
        exit.setText("EXIT");
        exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        cancelSelection.setForeground(new java.awt.Color(0, 0, 204));
        cancelSelection.setText("CLEAR SELECTION");
        cancelSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSelectionActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("STANDARD EXAM");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("CHOOSE THREE SUBJECTS");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Name:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(26, 26, 26))
            .addComponent(subjectPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cancelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exit, start});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(subjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(exit))
                .addGap(19, 19, 19))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {exit, start});

    }// </editor-fold>//GEN-END:initComponents

    private void cancelSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSelectionActionPerformed
        // TODO add your handling code here:
    for(int i = 0; i < subjectBox.length; i++)
        {
            subjectBox[i].setSelected(false);
            

        }
    }//GEN-LAST:event_cancelSelectionActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_exitActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        checkNameValidity();
        checkNumberOfSubjectsSelected();
        if(numberOfSubjects != 3)
        {
            JOptionPane.showMessageDialog(standardized.this, "Please choose three subjects");
        }
          else  if(!isNameValid)
        {
           JOptionPane.showMessageDialog(null, "Enter two of your names with a space in between", "UTMESOFT", JOptionPane.INFORMATION_MESSAGE, Utility.getIcon());
       }
        else
        {
            buildQuestionInfo();
        }
    }//GEN-LAST:event_startActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nameFieldActionPerformed
private void checkNumberOfSubjectsSelected()
    {
        numberOfSubjects =  0;
        for(int i = 0; i < subjectBox.length; i++)
        {
            if(subjectBox[i].isSelected() == true)
            {
                numberOfSubjects++;
            }
        }
     }
private void checkNameValidity()
    {
        nameOfStudent = nameField.getText();
        String reg = "[A-Za-z]{2,}[ ][A-Za-z]{2,}";
        isNameValid = nameOfStudent.matches(reg);
    }
private void buildQuestionInfo()
    {

        String [] subjectNames = getSelectedSubjects();
        nameOfStudent = nameField.getText();
        QuestionInfo questionInfo = new QuestionInfo(4, 50,  subjectNames, 150, nameOfStudent);
        String information = "<html><b><font color=#ff0000>Dear " + nameOfStudent + ", You have chosen the following subjects ";
        for(int i =0; i < subjectNames.length; i++)
        {
            information += ("           <br><font color=#0000ff>" + subjectNames[i]);
        }
        information += ("           <br><font color=#000000>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Click yes to continue");
        int n = JOptionPane.showConfirmDialog(null, information, "UTMESOFT", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, Utility.getIcon());
        if(n == 0)
        {
        QuestionsDialog dialog = new QuestionsDialog(new JFrame(), true, questionInfo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                dialog.setVisible(true);
        }
    }

    private String[] getSelectedSubjects()
    {
      String selectedSubjects [] = new String[4];
         selectedSubjects[0] = "English";
          int index = 1;
           for(int i = 0; i < subjectBox.length; i++)
              {
                  if(subjectBox[i].isSelected())
                  {
                    selectedSubjects[index] = subjectBox[i].getText();
                    index++;
                  }
              }
             
      return selectedSubjects;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelSelection;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton start;
    private javax.swing.JPanel subjectPanel;
    // End of variables declaration//GEN-END:variables

}
